// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/xopoww/chess2pic/models"
)

// PostPgnOKCode is the HTTP code returned for type PostPgnOK
const PostPgnOKCode int = 200

/*
PostPgnOK API call result

swagger:response postPgnOK
*/
type PostPgnOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIResult `json:"body,omitempty"`
}

// NewPostPgnOK creates PostPgnOK with default headers values
func NewPostPgnOK() *PostPgnOK {

	return &PostPgnOK{}
}

// WithPayload adds the payload to the post pgn o k response
func (o *PostPgnOK) WithPayload(payload *models.APIResult) *PostPgnOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post pgn o k response
func (o *PostPgnOK) SetPayload(payload *models.APIResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPgnOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
