// Code generated by go-swagger; DO NOT EDIT.

// Package restapi chess2pic
//
//	chess2pic REST API server
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/gif
//	  - image/png
//	  - application/json
//
// swagger:meta
package restapi
