// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "chess2pic REST API server",
    "title": "chess2pic",
    "version": "1.0.0"
  },
  "paths": {
    "/fen": {
      "post": {
        "summary": "Convert FEN position to PNG image",
        "parameters": [
          {
            "description": "FEN visualization request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "notation",
                "from-white"
              ],
              "properties": {
                "from-white": {
                  "description": "visualize form white's persective",
                  "type": "boolean"
                },
                "notation": {
                  "description": "Chess position in FEN notation",
                  "type": "string"
                }
              },
              "example": {
                "from-white": true,
                "notation": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "API call result",
            "schema": {
              "$ref": "#/definitions/ApiResult"
            }
          }
        }
      }
    },
    "/pgn": {
      "post": {
        "summary": "Convert PGN game to GIF animation",
        "parameters": [
          {
            "description": "PGN visualization request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "notation",
                "from-white"
              ],
              "properties": {
                "from-white": {
                  "description": "visualize form white's persective",
                  "type": "boolean"
                },
                "notation": {
                  "description": "Chess game in PGN notation",
                  "type": "string"
                }
              },
              "example": {
                "from-white": true,
                "notation": "[FEN \"k7/1p6/8/8/8/8/6P1/7K w - - 0 1\"]\n\n1. g4 b5 2. g5 b4"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "API call result",
            "schema": {
              "$ref": "#/definitions/ApiResult"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResult": {
      "type": "object",
      "required": [
        "ok"
      ],
      "properties": {
        "error": {
          "description": "Human-readable description of an error",
          "type": "string"
        },
        "ok": {
          "description": "If ok is true, result is not empty, otherwise error is not empty",
          "type": "boolean"
        },
        "result": {
          "description": "Result image in base64 encoding",
          "type": "string",
          "format": "byte"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "chess2pic REST API server",
    "title": "chess2pic",
    "version": "1.0.0"
  },
  "paths": {
    "/fen": {
      "post": {
        "summary": "Convert FEN position to PNG image",
        "parameters": [
          {
            "description": "FEN visualization request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "notation",
                "from-white"
              ],
              "properties": {
                "from-white": {
                  "description": "visualize form white's persective",
                  "type": "boolean"
                },
                "notation": {
                  "description": "Chess position in FEN notation",
                  "type": "string"
                }
              },
              "example": {
                "from-white": true,
                "notation": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "API call result",
            "schema": {
              "$ref": "#/definitions/ApiResult"
            }
          }
        }
      }
    },
    "/pgn": {
      "post": {
        "summary": "Convert PGN game to GIF animation",
        "parameters": [
          {
            "description": "PGN visualization request",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "notation",
                "from-white"
              ],
              "properties": {
                "from-white": {
                  "description": "visualize form white's persective",
                  "type": "boolean"
                },
                "notation": {
                  "description": "Chess game in PGN notation",
                  "type": "string"
                }
              },
              "example": {
                "from-white": true,
                "notation": "[FEN \"k7/1p6/8/8/8/8/6P1/7K w - - 0 1\"]\n\n1. g4 b5 2. g5 b4"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "API call result",
            "schema": {
              "$ref": "#/definitions/ApiResult"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResult": {
      "type": "object",
      "required": [
        "ok"
      ],
      "properties": {
        "error": {
          "description": "Human-readable description of an error",
          "type": "string"
        },
        "ok": {
          "description": "If ok is true, result is not empty, otherwise error is not empty",
          "type": "boolean"
        },
        "result": {
          "description": "Result image in base64 encoding",
          "type": "string",
          "format": "byte"
        }
      }
    }
  }
}`))
}
